version: '3.1'
services:
  db:
    image: postgres:14-alpine
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    restart: always
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - ${POSTGRES_PORT}:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
